name: rasterenv
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.1=py_0
  - appdirs=1.4.3=py_1
  - asn1crypto=0.24.0=py36_3
  - attrs=18.2.0=py_0
  - automat=0.7.0=py_1
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=2.1.4=py_1
  - bokeh=1.1.0=py36_0
  - boost=1.66.0=py36_vc14_1
  - boost-cpp=1.66.0=vc14_1
  - boto3=1.9.0=py_0
  - botocore=1.12.0=py_0
  - ca-certificates=2019.1.23=0
  - cartopy=0.16.0=py36hbd42bde_0
  - certifi=2019.3.9=py36_0
  - cffi=1.11.5=py36hfa6e2cd_1
  - click=6.7=py_1
  - click-plugins=1.0.3=py_1
  - cligj=0.4.0=py_1
  - cloudpickle=1.0.0=py_0
  - colorama=0.3.9=py_1
  - colorcet=2.0.1=py_0
  - constantly=15.1.0=py_0
  - cryptography=2.3.1=py36h74b6da3_0
  - cryptography-vectors=2.3.1=py36_0
  - curl=7.60.0=vc14_0
  - cycler=0.10.0=py_1
  - cython=0.28.5=py36h6538335_0
  - cytoolz=0.9.0.1=py36hfa6e2cd_1
  - dask=1.2.2=py_0
  - dask-core=1.2.2=py_0
  - datashader=0.7.0=py_0
  - datashape=0.5.4=py36_1
  - decorator=4.3.0=py_0
  - descartes=1.1.0=py36_0
  - distributed=1.28.1=py36_0
  - docutils=0.14=py36_1
  - entrypoints=0.2.3=py36_2
  - expat=2.2.5=vc14_0
  - fiona=1.7.10=py36h5bf8d1d_0
  - freetype=2.9.1=he8b6a0d_4
  - freexl=1.0.2=vc14_2
  - gdal=2.2.4=py36h2fc6367_1
  - geopandas=0.4.1=py_0
  - geos=3.6.2=he025d50_3
  - geotiff=1.4.2=vc14_1
  - geoviews=1.6.2=py_0
  - geoviews-core=1.6.2=py_0
  - hdf4=4.2.13=vc14_0
  - hdf5=1.10.1=vc14_2
  - heapdict=1.0.0=py36_2
  - holoviews=1.12.3=py_0
  - html5lib=1.0.1=py_0
  - hyperlink=17.3.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc14_0
  - idna=2.7=py36_2
  - imageio=2.5.0=py36_0
  - incremental=17.5.0=py_0
  - intel-openmp=2019.3=203
  - ipykernel=4.9.0=py36_0
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.1=py_0
  - jedi=0.12.1=py36_0
  - jinja2=2.10=py_1
  - jmespath=0.9.3=py_1
  - jpeg=9b=vc14_2
  - jsonschema=2.6.0=py36_2
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py_1
  - jupyter_console=5.2.0=py36_1
  - jupyter_core=4.4.0=py_0
  - kealib=1.4.7=vc14_4
  - kiwisolver=1.0.1=py36he980bc4_2
  - krb5=1.14.6=vc14_0
  - libflang=5.0.0=vc14_20180208
  - libgdal=2.2.4=vc14_5
  - libiconv=1.14=vc14_4
  - libnetcdf=4.6.1=vc14_2
  - libpng=1.6.34=vc14_0
  - libpq=9.6.3=vc14_0
  - libsodium=1.0.16=vc14_0
  - libspatialindex=1.8.5=h6538335_2
  - libspatialite=4.3.0a=vc14_19
  - libssh2=1.8.0=hc4dcbb0_2
  - libtiff=4.0.9=vc14_0
  - libxml2=2.9.5=vc14_1
  - libxslt=1.1.29=h0037b19_6
  - llvm-meta=5.0.0=0
  - llvmlite=0.24.0=py36h6538335_0
  - locket=0.2.0=py36hfed976d_1
  - lxml=4.1.1=py36he0adb16_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.0.1=py_0
  - markdown=3.1=py36_0
  - markupsafe=1.0=py36hfa6e2cd_1
  - matplotlib=2.2.3=py36h31860fd_0
  - mistune=0.8.3=py36hfa6e2cd_2
  - mkl=2018.0.3=1
  - mkl_fft=1.0.6=py36hdbbee80_0
  - mkl_random=1.0.1=py36h77b88f5_1
  - msgpack-python=0.5.6=py36he980bc4_1
  - msys2-conda-epoch=20160418=1
  - multipledispatch=0.6.0=py36_0
  - munch=2.3.2=py36_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - netcdf4=1.3.1=py36heef61c0_2
  - networkx=2.3=py_0
  - notebook=5.6.0=py36_1
  - numba=0.39.0=py36h830ac7b_0
  - numpy=1.15.4=py36ha559c80_0
  - numpy-base=1.15.4=py36h8128ebf_0
  - olefile=0.46=py36_0
  - openblas=0.2.20=vc14_8
  - openjpeg=2.3.0=vc14_2
  - openmp=5.0.0=vc14_1
  - openssl=1.0.2p=hfa6e2cd_0
  - owslib=0.17.1=py_0
  - packaging=19.0=py36_0
  - pandas=0.23.4=py36h830ac7b_0
  - pandoc=2.2.2=hde52d81_1
  - pandocfilters=1.4.2=py_1
  - panel=0.5.1=py_0
  - param=1.9.0=py_0
  - parso=0.3.1=py_0
  - partd=0.3.10=py36_1
  - pickleshare=0.7.4=py36_0
  - pillow=5.2.0=py36h08bbbbd_0
  - pip=18.0=py36_1
  - proj4=4.9.3=vc14_5
  - prometheus_client=0.3.0=py_0
  - prompt_toolkit=1.0.15=py_1
  - psutil=5.4.7=py36hfa6e2cd_0
  - psycopg2=2.7.3.1=py36h308da27_0
  - pyasn1=0.4.4=py_0
  - pyasn1-modules=0.2.1=py_0
  - pycparser=2.18=py_1
  - pyct=0.4.6=py_0
  - pyct-core=0.4.6=py_0
  - pyepsg=0.4.0=py36_0
  - pygments=2.2.0=py_1
  - pyhamcrest=1.9.0=py_2
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py_1
  - pyproj=1.9.5.1=py36haf3c679_3
  - pyqt=5.6.0=py36h764d66f_7
  - pyshp=2.1.0=py_0
  - pysocks=1.6.8=py36_2
  - python=3.6.6=he025d50_0
  - python-dateutil=2.7.3=py_0
  - pytz=2018.5=py_0
  - pyviz_comms=0.7.2=py_0
  - pywavelets=1.0.0=py36h452e1ab_0
  - pywin32=223=py36hfa6e2cd_0
  - pywinpty=0.5.4=py36_1
  - pyyaml=3.13=py36hfa6e2cd_0
  - pyzmq=17.1.2=py36hf576995_0
  - qt=5.6.2=vc14_1
  - qtconsole=4.4.1=py36_1
  - rasterio=1.0.3=py36hfa10f2d_0
  - requests=2.21.0=py36_0
  - rtree=0.8.3=py36_0
  - scikit-image=0.14.0=py36h6538335_1
  - send2trash=1.5.0=py_0
  - service_identity=17.0.0=py_0
  - setuptools=40.2.0=py36_0
  - shapely=1.6.4=py36hc90234e_1
  - simplegeneric=0.8.1=py_1
  - sip=4.18.1=py36h6538335_0
  - six=1.11.0=py36_1
  - snuggs=1.4.1=py_1
  - sortedcontainers=2.1.0=py36_0
  - sqlalchemy=1.2.11=py36hfa6e2cd_0
  - sqlite=3.20.1=vc14_2
  - tblib=1.4.0=py_0
  - terminado=0.8.1=py36_1
  - testpath=0.3.1=py36_1
  - tk=8.6.8=hfa6e2cd_0
  - toolz=0.9.0=py36_0
  - tornado=5.1=py36hfa6e2cd_1
  - traitlets=4.3.2=py36_0
  - twisted=18.7.0=py36hfa6e2cd_1
  - urllib3=1.23=py36_1
  - vc=14=0
  - vs2015_runtime=14.0.25420=0
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.31.1=py36_1
  - widgetsnbextension=3.4.1=py36_0
  - win_inet_pton=1.0.1=py36_2
  - wincertstore=0.2=py36_2
  - winpty=0.4.3=4
  - xarray=0.12.1=py_0
  - xerces-c=3.2.0=vc14_0
  - xz=5.2.4=h2fa13f4_1
  - yaml=0.1.7=hc54c509_2
  - zeromq=4.2.5=vc14_2
  - zict=0.1.4=py36_0
  - zlib=1.2.11=vc14_0
  - zope.interface=4.5.0=py36hfa6e2cd_1
  - pip:
    - chardet==3.0.4
    - future==0.16.0
    - goespy==0.2.1
    - hs-restclient==1.3.1
    - oauthlib==3.0.1
    - pathlib==1.0.1
    - pygeoprocessing==1.2.3
    - pygeotools==0.5.0
    - requests-oauthlib==1.2.0
    - requests-toolbelt==0.9.1
    - s3transfer==0.1.13
    - scipy==1.1.0
prefix: C:\Users\steve\Anaconda3\envs\rasterenv

